/** Same labels as wanderly `FilterScreen.tsx` filterOptions (tripType matching on wanderly-1). */
export const TRIP_TYPE_FILTER_OPTIONS = [
  "Adventure",
  "Relaxation",
  "Cultural",
  "Nature",
  "Road",
  "Backpacking",
  "Cruise",
  "Luxury",
  "Solo",
  "Family",
  "Romantic",
  "Group",
  "Business",
  "Wellness",
  "Food & Wine",
  "Volunteer",
  "Spiritual",
  "Festival",
  "Staycation",
  "Digital Nomad",
  "Others",
] as const;
